logging:
  file: logs/cloud-web.log
  level:
    root: info
    com.dsjk.platform: debug

server:
  port: 3333

spring:
  application:
    name: cloud-web
  aop:
    proxy-target-class: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true



