# log
logging:
  file: logs/cloud-web.log
  level:
    root: info
    com.dsjk.platform: debug

server:
  port: 3333

spring:
  application:
    name: cloud-web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true

# 增加Spring Boot Info端点信息
# http://localhost:8010/info
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@


