logging:
  file: logs/cloud-web.log
  level:
    root: info
    com.cheng.platform: debug

server:
  port: 3333

spring:
  application:
    name: cloud-web
  aop:
    proxy-target-class: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false

feign:
  httpclient:
    enabled: true