#login
logging:
  file: logs/cloud-config-server.log
  level:
    root: info
    com.dsjk.config: debug

server:
  port: 6666

spring:
  application:
    name: config-server

# git管理配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lufengc/platform-cloud
          searchPaths: config-repo
          username: lufengc@163.com
          password: fengcheng1991

