#login
logging:
  file: logs/cloud-config-server.log
  level:
    root: info
    com.dsjk.config: debug

server:
  port: 6666

spring:
  application:
    name: config-server

  # git管理配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lufengc/platform-cloud
          searchPaths: config-repo
          username: lufengc@163.com
          password: fengcheng1991

    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    prefer-ip-address: true
