# log
logging:
  file: logs/cloud-config-server.log
  level:
    root: info
    com.dsjk.platform: debug

server:
  port: 6666

spring:
  application:
    name: config-server

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lufengc/platform-cloud
          searchPaths: config-repo
          username: username
          password: password