server:
  port: 5555

spring:
  application:
    name: api-gateway

# routes to url
zuul:
  routes:
    api-web:
      path: /api-web/**
      serviceId: cloud-web

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/